name: CI

on:
    push:
        branches:
            - main
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            - run: cargo fmt --all -- --check
            - run: cargo clippy --all-features --all-targets -- -D warnings
            - run: cargo check --all-features --all-targets

    run:
        name: Bench
        needs: [check]
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            - run: cargo bench
